name: Convert JSON to Table

on:
   workflow_call:

jobs:
  get_snapshot_of_extensions:
    outputs: 
      get_extensions_apiCall: ${{ steps.get_extensions_snapshot.outputs.get_extensions_apiCall }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - id: get_extensions_snapshot
      run: |
             get_extensions_apiCall=`curl  --request GET \
                               --header 'Authorization: Basic Qk9PTUlfVE9LRU4ua2FydGlrLmRhc2hvcmFAbmVvc2FscGhhLmNvbTo1Y2JkNmFlYi03NzI3LTRmZmQtODEyYi02OTI3NjI3NzMyYTk=' \
                               --header 'accept: application/json' \
                               --url 'https://api.boomi.com/api/rest/v1/neosalpha-SSL1AK/EnvironmentExtensions/b8ece4bb-0306-45dc-8911-c31dd6e11d14'`
                               
                             
                               echo $get_extensions_apiCalls
                               a="{
                                    	"@type": "EnvironmentExtensions",
                                    	"connections": {
                                    		"@type": "Connections",
                                    		"connection": [
                                    			{
                                    				"@type": "Connection",
                                    				"field": [
                                    					{
                                    						"@type": "Field",
                                    						"id": "authType",
                                    						"encryptedValueSet": false,
                                    						"usesEncryption": false,
                                    						"componentOverride": false,
                                    						"useDefault": true
                                    					},
                                    					{
                                    						"@type": "Field",
                                    						"id": "oauthOptions/OAuth2Config/credentials/@clientId",
                                    						"encryptedValueSet": false,
                                    						"usesEncryption": false,
                                    						"componentOverride": false,
                                    						"useDefault": true
                                    					},
                                    					{
                                    						"@type": "Field",
                                    						"id": "oauthOptions/OAuth2Config/credentials/@clientSecret",
                                    						"encryptedValueSet": false,
                                    						"usesEncryption": false,
                                    						"componentOverride": false,
                                    						"useDefault": true
                                    					},
                                    					{
                                    						"@type": "Field",
                                    						"id": "oauthOptions/OAuth2Config/credentials/@accessToken",
                                    						"encryptedValueSet": false,
                                    						"usesEncryption": true,
                                    						"componentOverride": false,
                                    						"useDefault": true
                                    					}
                                    				],
                                    				"id": "4d3f80eb-5a5e-421e-b596-c5a56e739607",
                                    				"name": "Boomi_Service_Slack_Connector"
                                    			}
                                    		]
                                    	},
                                    	"environmentId": "b8ece4bb-0306-45dc-8911-c31dd6e11d14",
                                    	"extensionGroupId": "",
                                    	"id": "b8ece4bb-0306-45dc-8911-c31dd6e11d14"
                                    }"
                               echo "get_extensions_apiCall=$a" >> $GITHUB_OUTPUT

  convert_json_to_table:
    needs: get_snapshot_of_extensions
    runs-on: ubuntu-latest
    steps:
                              
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
       
    - name: Convert JSON to Table
      run: |
            echo ${{ needs.get_snapshot_of_extensions.outputs.get_extensions_apiCall }}
            python convert_json_to_table.py "${{ needs.get_snapshot_of_extensions.outputs.get_extensions_apiCall }}"

    - name: Commit and push changes
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git add .
        git commit -m "Convert JSON to Table"
        git push
