name: Convert JSON to Table

on:
   workflow_call:

jobs:
  get_snapshot_of_extensions:
    outputs: 
      get_extensions_apiCall: ${{ steps.get_extensions_snapshot.outputs.get_extensions_apiCall }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - id: get_extensions_snapshot
      run: |
             get_extensions_apiCall=`curl  --request GET \
                               --header 'Authorization: Basic Qk9PTUlfVE9LRU4ua2FydGlrLmRhc2hvcmFAbmVvc2FscGhhLmNvbTo1Y2JkNmFlYi03NzI3LTRmZmQtODEyYi02OTI3NjI3NzMyYTk=' \
                               --header 'accept: application/json' \
                               --url 'https://api.boomi.com/api/rest/v1/neosalpha-SSL1AK/EnvironmentExtensions/b8ece4bb-0306-45dc-8911-c31dd6e11d14'`
                               
                             
                               echo $get_extensions_apiCall 
                              echo $get_extensions_apiCall, >> ProcessInfo/SnapshotInitial.json
                                            git config user.name ashmitasawant
                                            git config user.email ashmitasawant3@gmail.com
                                            git add .
                                            git commit -m "Published Changes"
                                            git push --force origin main   

  convert_json_to_table:
    needs: get_snapshot_of_extensions
    runs-on: ubuntu-latest
    steps:
                              
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirement.txt
       
    - name: Convert JSON to Table
      run: |
            echo ${{ needs.get_snapshot_of_extensions.outputs.get_extensions_apiCall }}
            python convert_json_to_table.py 

    # - name: Commit and push changes
    #   run: |
    #     git config user.name "${{ github.actor }}"
    #     git config user.email "${{ github.actor }}@users.noreply.github.com"
    #     git add .
    #     git commit -m "Convert JSON to Table"
    #     git push

    # - name: Commit and push changes
    #   run: |
    #     git config --global user.email "ashmitasawant3@gmail.com"
    #     git config --global user.name "ashmitasawant"
    #     git add output.csv
    #     git commit -m "Update CSV file"
    #     git push
    - name: Upload CSV as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: converted-csv
        path: example.csv
