name: Pass Array Between Jobs

on:
  push:
   

jobs:
  define-array:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.set-array-output.outputs.array }}

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Set the array
      id: set-array-output
      run: |
        fileToBeRead=$(ls -1 ./ProcessInfo/ProcessDetails.TestProcess.test.json )
              echo "File To be Read is:" $fileToBeRead
              arrIN=(${fileToBeRead//// })
              fileToRead=$(echo ${arrIN[4]})
              echo $fileToRead
              echo "::set-output name=fileToRead::$fileToRead"
              fileRead=$(cat ./ProcessInfo/ProcessDetails.TestProcess.test.json)
              echo "File Data:"$fileRead
              extensionsToBeUpdate=$(echo  ${fileRead} | jq '.[] | .extensionsToUpdate[0:5]' | sed 's/[],[]//g' )
              extensionsToBeUpdateArray=$(echo $extensionsToBeUpdate)
              echo $extensionsToBeUpdateArray
              
              
              
              if [[ $extensionsToBeUpdateArray == *"connections"* ]]
              then
                    echo "String contains connections."
                    connections_flag=true
              else
                    echo "String does not contain connections."
                    connections_flag=false
              fi
              if [[ $extensionsToBeUpdateArray == *"dpps"* ]]
              then
                    echo "String contains dpps."
                    dpps_flag=true
              else
                    echo "String does not contain dpps."
                    dpps_flag=false
              fi
              if [[ $extensionsToBeUpdateArray == *"pps"* ]]
              then
                    echo "String contains pps."
                    pps_flag=true
              else
                    echo "String does not contain pps."
                    pps_flag=false
              fi
              
                 
 
