name: Deployment Pipeline

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  getProcessDetails:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Get ComponentId
        uses: actions/checkout@v2
      - id: setComponentId
        run: |
            ProcessDetails=$(cat ./ProcessDetails.json)
            componentId=$(echo  ${ProcessDetails} | jq '.[0].componentID')
            echo $componentId
     
            
  createPackage:
    needs: getProcessDetails
    environment: Dev
    env: 
      BOOMI_USERNAME: ${{ secrets.BOOMI_USERNAME }}
      BOOMI_PASSWORD: ${{ secrets.BOOMI_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
     - name: SetVariables
       run: |
            echo "The API key is:${{env.BOOMI_USERNAME}}"
            echo "ComponentId is" ${{steps.setComponentId.outputs.componentId}}
  
        
