name: Deployment Pipeline

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  getProcessDetails:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.setComponentId.outputs.cID }}
      output2: ${{ steps.setComponentId.outputs.API_Response }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Get ComponentId
        uses: actions/checkout@v2
      - id: setComponentId
        run: |
            ProcessDetails=$(cat ./ProcessDetails.json)
            componentId=$(echo  ${ProcessDetails} | jq '.[0].componentID')
            echo "::set-output name=cID::$componentId"
  
            
  createPackage:
    
    environment: Dev
    env: 
      BOOMI_USERNAME: ${{ secrets.BOOMI_USERNAME }}
      BOOMI_PASSWORD: ${{ secrets.BOOMI_PASSWORD }}
     
    runs-on: ubuntu-latest
    needs: getProcessDetails
    steps:
     - name: SetVariables
       id: showVariable
       run:   echo ${{needs.getProcessDetails.outputs.output1}}
     - name: Package Creation
       id: packageCreation
       uses: fjogeleit/http-request-action@master
       with:
        url: 'https://api.boomi.com/api/rest/v1/neosalpha-SSL1AK/PackagedComponent'
        method: 'POST'
        contentType: 'application/json'
        customHeaders: '{"accept": "application/json"}'
        data: '{"componentId": ${{needs.getProcessDetails.outputs.output1}},"packageVersion":"1.18", "notes":"Package for deployment" }'
        username: ${{env.BOOMI_USERNAME}}
        password: ${{env.BOOMI_PASSWORD}}
        
     - name: Show Response
       run: |
           echo "::set-output name=API_Response::${{ steps.packageCreation.outputs.response }}"
           echo  ${{needs.getProcessDetails.outputs.output2}}
          
