name: Deployment Pipeline

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  getProcessIds:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    outputs:
      output1: ${{ steps.setComponentId.outputs.componentID }}


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Get ComponentId
        uses: actions/checkout@v2
      - id: setComponentId
        run: |
            ProcessDetails=$(cat ./ProcessDetails.json)
            componentId=$(echo  ${ProcessDetails} | jq '.[0].componentID')
            echo "::set-output name=componentID::$componentId"
  
            
  createPackage:
    
    environment: Dev
    env: 
      BOOMI_USERNAME: ${{ secrets.BOOMI_USERNAME }}
      BOOMI_PASSWORD: ${{ secrets.BOOMI_PASSWORD }}
     
    runs-on: ubuntu-latest
    outputs:
      output2: ${{ steps.response.outputs.packageId }}
    needs: getProcessIds
    steps:
     - name: SetVariables
       id: showVariable
       run:   echo ${{needs.getProcessIds.outputs.output1}}
       
     - name: Package Creation
       id: packageCreation
       uses: fjogeleit/http-request-action@master
       with:
        url: 'https://api.boomi.com/api/rest/v1/neosalpha-SSL1AK/PackagedComponent'
        method: 'POST'
        contentType: 'application/json'
        customHeaders: '{"accept": "application/json"}'
        data: '{"componentId": ${{needs.getProcessIds.outputs.output1}},"packageVersion":"1.53", "notes":"Package for deployment" }'
        username: ${{env.BOOMI_USERNAME}}
        password: ${{env.BOOMI_PASSWORD}}
        
     - name: Show Response
       id: response
       run: |
            packageID=$(echo ${{ toJSON(steps.packageCreation.outputs.response) }} | jq ".packageId")
            echo "::set-output name=packageId::$packageID"
            
        
  pushPackageIds:

      runs-on: ubuntu-latest    
      needs: createPackage
      steps:
        - uses: actions/checkout@v2
        - name: pushPackageIds
          id: packageId
          run: |
               echo ${{needs.createPackage.outputs.output2}} 
               echo ${{needs.createPackage.outputs.output2}} >> PackageIds.txt
               git config user.name ashmitasawant
               git config user.email ashmitasawant3@gmail.com
               git add .
               git commit -m "Published Changes"
               git push
       
  deployPackage: 
   environment: Dev
   env: 
        BOOMI_USERNAME: ${{ secrets.BOOMI_USERNAME }}
        BOOMI_PASSWORD: ${{ secrets.BOOMI_PASSWORD }}
   runs-on: ubuntu-latest    
   needs: createPackage    
   steps:     
     - name: Package Deploy
       id: packageDeploy
       uses: fjogeleit/http-request-action@master
       with:
         url: 'https://api.boomi.com/api/rest/v1/neosalpha-SSL1AK/DeployedPackage'
         method: 'POST'
         contentType: 'application/json'
         customHeaders: '{"accept": "application/json"}'
         data: '{"environmentId": "b3af1cf6-f33c-4539-bac5-e69073703311","packageId": ${{needs.createPackage.outputs.output2}}}'
         username: ${{env.BOOMI_USERNAME}}
         password: ${{env.BOOMI_PASSWORD}}
           
     - name: Show Response
       id: response
       run: |
            response=$(echo ${{ toJSON(steps.packageDeploy.outputs.response) }})
            echo $response
   
